alter table Player drop foreign key FK_ks4oof9guph2qvo7v6cqdiefx;
alter table PlayerCharacter drop foreign key FK_1wbxymbhm40bq5goo5laqy756;
alter table PlayerCharacter drop foreign key FK_2tvilr6gkaifhe9fei568ij7b;
alter table PlayerCharacter_TraitChanges drop foreign key FK_s5e9fv5uoth36s44agn30vqtt;
alter table PlayerCharacter_TraitChanges drop foreign key FK_ebyhdsyremvpge52v5g3ckdqt;
alter table TraitChanges drop foreign key FK_9wqbr22xdk46h0hhshrotsv9k;
alter table TraitChanges drop foreign key FK_1soleuoltintdme7o8cj8qmis;
drop table if exists AuditEvent;
drop table if exists Player;
drop table if exists PlayerCharacter;
drop table if exists PlayerCharacter_TraitChanges;
drop table if exists TraitChanges;
drop table if exists Troupe;
create table AuditEvent (id varchar(255) not null, audit_message varchar(255), audited_type varchar(255), audited_id varchar(255), timestamp datetime, primary key (id));
create table Player (id varchar(255) not null, deleted_at datetime, email varchar(255), name varchar(255), troupe_id varchar(255), primary key (id));
create table PlayerCharacter (id varchar(255) not null, deleted_at datetime, name varchar(255), player_id varchar(255), troupe_id varchar(255), primary key (id));
create table PlayerCharacter_TraitChanges (PlayerCharacter_id varchar(255) not null, traitChangeEvents_id varchar(255) not null, order_by integer not null, primary key (PlayerCharacter_id, order_by));
create table TraitChanges (trait_change_type varchar(31) not null, id varchar(255) not null, status integer, child_id varchar(255), traitToRemove_id varchar(255), primary key (id));
create table Troupe (id varchar(255) not null, deleted_at datetime, name varchar(255), setting integer, primary key (id));
alter table PlayerCharacter_TraitChanges add constraint UK_s5e9fv5uoth36s44agn30vqtt  unique (traitChangeEvents_id);
alter table Player add constraint FK_ks4oof9guph2qvo7v6cqdiefx foreign key (troupe_id) references Troupe (id);
alter table PlayerCharacter add constraint FK_1wbxymbhm40bq5goo5laqy756 foreign key (player_id) references Player (id);
alter table PlayerCharacter add constraint FK_2tvilr6gkaifhe9fei568ij7b foreign key (troupe_id) references Troupe (id);
alter table PlayerCharacter_TraitChanges add constraint FK_s5e9fv5uoth36s44agn30vqtt foreign key (traitChangeEvents_id) references TraitChanges (id);
alter table PlayerCharacter_TraitChanges add constraint FK_ebyhdsyremvpge52v5g3ckdqt foreign key (PlayerCharacter_id) references PlayerCharacter (id);
alter table TraitChanges add constraint FK_9wqbr22xdk46h0hhshrotsv9k foreign key (child_id) references TraitChanges (id);
alter table TraitChanges add constraint FK_1soleuoltintdme7o8cj8qmis foreign key (traitToRemove_id) references TraitChanges (id);
